### ISSUE TITLE
Injection doesn't work

### ISSUE THREAD

**Issue by apan65** [isJuhn/KAMI#18]
Kami status always "unconnected"

**Comment by isJuhn** [comment]
You need to use custom version of RPCS3 for now: https://github.com/isjuhn/rpcs3/tree/IPC
With PCSX2 it should work on latest dev builds with IPC enabled.

**Comment by apan65** [comment]
Thanks for the helping. You should write in description about this nuance

**Comment by apan65** [comment]
Hello again, can you upload somewhere latest ipc implemented rpcs3 build?

**Comment by isJuhn** [comment]
Under artifacts here https://cirrus-ci.com/task/5704510594088960

**Comment by apan65** [comment]
> 
> 
> Under artifacts here https://cirrus-ci.com/task/5704510594088960

Still "unconnected" status

**Comment by isJuhn** [comment]
Did you build newest version of KAMI?

**Comment by apan65** [comment]
> Did you build newest version of KAMI?

No, can you publish it in "releases" there is latest v0.0.1

**Comment by apan65** [comment]
thanks, now it's working fine.

**Comment by apan65** [comment]
> done

well, i had new issue. Now when i start injection mouse looking just not work. I had try it in resistance 2 and rdr.

**Comment by Grugos** [comment]
Good morning, I apologize for my ignorance. I downloaded KAMI 0.0.6 and have RPCS3 v0.0.31, but KAMI keeps telling me "unconnected".

I have already tried starting KAMI first then RPCS3, and vice versa.
I have enabled IPC (port 25001).
I've already tried starting the game (Killzone 2 and 3) and then starting KAMI, and other variations

What can I do?
Thank you
