### ISSUE TITLE
Is it possible to get an update that could add Call of Duty 3 to the supported list

### ISSUE THREAD

**Issue by TheOldKingCole** [isJuhn/KAMI#23]
Cod 3 is still the only COD release to never get a pc release and so I think it would be pretty cool to be able to play it with mouse and keyboard

**Comment by isJuhn** [comment]
initial support for BLES00016 added in latest update

**Comment by TheOldKingCole** [comment]
Awesome thanks, also when can we hope to see a prebuilt version of the ipc RPCS3 build because I have no idea how to build from master even after reading the instructions, they just flew over my head I'm not good with that sort of thing

**Comment by MojoJojoDojo** [comment]
I wonder if its possible to support either Xemu or CXBX-R the Xbox emulators .
You can run COD3 on either too.

**Comment by UserGit-2021** [comment]
> 
> 
> initial support for BLES00016 added in latest commit

Will there be support for the XENIA emulator?

**Comment by isJuhn** [comment]
perhaps in the far future, but nothing planned

**Comment by isJuhn** [comment]
closing as fixed
