### ISSUE TITLE
types.hpp issue when building 

### ISSUE THREAD

**Issue by Bondedrobin** [isJuhn/KAMI#30]
Hi Johan,
I'm trying to build your ICP version of RPCS3 from source (I get that I may be in the wrong thread for that, GH is unintuitive for dummies like me). I installed all the dependencies, made sure the environment variables were right, and the issue I'm running into all comes down to whatever 'bit' is and the file rpcs3\rpcs3\util\types.hpp . I know nothing about C++. Here's the log:
https://pastebin.com/s2rQDcWn
Thank you!

**Comment by isJuhn** [comment]
Looks like you are using an old version of visual studio which isn't compatible with RPCS3. In any case there is a windows build here under artifacts https://cirrus-ci.com/task/5704510594088960 which comes from the IPC pull request https://github.com/RPCS3/rpcs3/pull/10522. Just make sure you build the current KAMI code and you should be fine.
