### ISSUE TITLE
I know im gonna sound dumb but, i literally can't find the download button for the ipc build. can someone send me it?

### ISSUE THREAD

**Issue by Bateman34** [isJuhn/KAMI#36]

**Comment by slug9011** [comment]
> https://api.cirrus-ci.com/v1/artifact/task/5840108847890432/Artifact/rpcs3-v0.0.17-98091dc7_win64.7z

The link is 404'ed and im having the same problem at bateman

**Comment by Bateman34** [comment]
There is no download link you have to build it yourself.

**Comment by isJuhn** [comment]
rebased it, download under artifacts https://cirrus-ci.com/task/5856306299928576
