### ISSUE TITLE
KAMI can't detect Ratchet: Deadlocked on PCSX2

### ISSUE THREAD

**Issue by OnceACodeMonkey** [isJuhn/KAMI#37]
The KAMI Status never gets past Unconnected.
Used KAMI v0.0.2
I installed .Net 5.0.11
I used PCSX2 1.7.0 dev 1177
I enabled IPC and set the port to 28012

Was there something I missed?

**Comment by isJuhn** [comment]
It might only work in multiplayer, unsure

**Comment by OnceACodeMonkey** [comment]
Rebooting didn't seem to work.

Also, I tried it in multiplayer, too. It didn't work there, either.

I think I installed the wrong version of .Net, because after I installed the desktop app version instead of the console app version, it started crashing instead of doing nothing. I suppose that means that now, my issue is the same as #31, so I should probably close this.

Although unlike RPCS3 playing Resistance, Kami isn't even registering that PCSX2 is open before it crashes. The Info section is always blank.
