### ISSUE TITLE
[Killzone 2][BCES00081] The injection doesn't work on update 01.29

### ISSUE THREAD

**Issue by BFG1992** [isJuhn/KAMI#43]
After updating the European version of Killzone 2 to update 01.29, the injection doesn't work anymore. Pressing the bound On/Off button locks the cursor in place, but there's no reaction to mouse movements of the ingame camera. Everything works properly in the non-updated game (version 01.01).

This is particularily important because the patch for removal of some effects and allowing the game to be played without enabling Write Color Buffers (and thus improving performance) is available for version 01.29 only.

I haven't tested the update 01.28 or other version of the game, though.

**Comment by slickmann** [comment]
tested it and it is still not working, bummer

**Comment by isJuhn** [comment]
Fixed as of #49 
Download new 0.0.3 release to test

**Comment by slickmann** [comment]
It works, you are a gift to mankind. You made so many people very happy for reliving one of their favorite games on PC. Thank you a million times over for the work you do.

**Comment by slickmann** [comment]
there is a small kink, it keeps crashing the emulator, tested with two different ipc builds.

run 1: F {PPU[0x1000000] Thread (main_thread) [0x00253cb8]} VM: Access violation reading location 0x3bc49c94 (unmapped memory)

run 2: F {PPU[0x1000000] Thread (main_thread) [0x00254054]} VM: Access violation reading location 0xbb4499d5 (unmapped memory)

run 3: F {PPU[0x1000000] Thread (main_thread) [0x002056b8]} VM: Access violation reading location 0xba830eb6 (unmapped memory)

run 4:F {PPU[0x1000000] Thread (main_thread) [0x00254054]} VM: Access violation reading location 0x3b9375a7 (unmapped memory)

run 5: F {PPU[0x1000000] Thread (main_thread) [0x00253cb8]} VM: Access violation reading location 0x3a0319e5 (unmapped memory)

**Comment by slickmann** [comment]
In the brief time that the injector is working, I tested it on a gun turret and it totally wrecks it.
