### ISSUE TITLE
KAMI status: Unconnected

### ISSUE THREAD

**Issue by Vladzor87do** [isJuhn/KAMI#53]
I have an issue, get status Unconnected while playing Killzone 2 on RPCS3 0.0.22 13635-7c8fbc35 Alpha master
Kami is not really working
![Screenshot 2022-05-22 201605](https://user-images.githubusercontent.com/63660560/169709839-4ff65841-c1a7-4a64-a67b-b226e2733af6.png)

What i am doing wrong ?

**Comment by Bateman34** [comment]
You need the special IPC build which is impossible to get unless you know how to build your own version.

**Comment by Vladzor87do** [comment]
so Kami is useless for official RPCS3 builds ?

**Comment by dio-gh** [comment]
Correct, requires the IPC PR build.

**Comment by isJuhn** [comment]
IPC has been merged into mainline rpcs3, use build 0.0.22-13800 or newer
