### ISSUE TITLE
Question - How does this differ from manually settings kb/m bindings in-emulator?

### ISSUE THREAD

**Issue by CrossbowDemon** [isJuhn/KAMI#73]
I am genuinely curious what the difference is between using this program and manually setting in-emulator k/m bindings?

**Comment by dio-gh** [comment]
The emulator will map your mouse input to a virtual joystick, which is then interpreted by the game. This gives a nauseating experience.

KAMI instead calculates new angles for the active game camera and injects them into game memory. This gives a native mouse movement implementation feel.
