### ISSUE TITLE
The program doesn't recognize installed frameworks.

### ISSUE THREAD

**Issue by UberZer0** [isJuhn/KAMI#76]
From the link, I downloaded SDK which included the necessary runtimes however program always prompts me to get it.
![Ekran görüntüsü 2023-03-08 032037](https://user-images.githubusercontent.com/32621990/223586646-02b3d978-d8c8-4e18-8ecc-b10f0549706b.png)

**Comment by isJuhn** [comment]
try open cmd and run `dotnet --list-sdks` and `dotnet --list-runtimes` and show results

**Comment by UberZer0** [comment]
[cid:78d015dd-7fbb-481d-8311-7a225c6bd717]
Here you go, thank you.
________________________________
Gönderen: Johan Hellgren ***@***.***>
Gönderildi: 9 Mart 2023 Perşembe 01:26
Kime: isJuhn/KAMI ***@***.***>
Bilgi: UberZer0 ***@***.***>; Author ***@***.***>
Konu: Re: [isJuhn/KAMI] The program doesn't recognize installed frameworks. (Issue #76)


try open cmd and run dotnet --list-sdks and dotnet --list-runtimes and show results

**Comment by UberZer0** [comment]
![thumbnail_image](https://user-images.githubusercontent.com/32621990/223873994-1a030801-dd0d-4825-b555-e554e9a204cf.png)
Here you go, I think sending it by mail somehow made it worse.

**Comment by isJuhn** [comment]
I guess maybe latest release is still on .net 6 (we have no automatic release pipeline) try downloading the artifacts for the top result in the Actions tab. Or build from source. Or install .net 6.

**Comment by UberZer0** [comment]
That one worked, thank you.
