### ISSUE TITLE
Toggle not working when main window is active

### ISSUE THREAD

**Issue by RashataanVuul** [isJuhn/KAMI#86]
Hello! I have this weird problem and I'm not sure if it's an issue with KAMI or the emulator itself but using PCSX2 Nightly - 1.7.4724 with PINE enabled, the toggle hotkey doesn't seem to work when PCSX2 window is active. When I switch to the KAMI window, the toggle works fine and the mouse injector works. However, when I ALT+TAB back to the PCSX2 window, it just spazzes out.

This was while I was testing Ratchet & Clank: Up Your Arsenal

**Comment by RashataanVuul** [comment]
Nevermind. The issue was the fact that I was running the emulator as admininstrator and running the emulator normally fixed the problem. Delete this if possible

**Comment by isJuhn** [comment]
Interesting but predictable issue. Applications launched in non-privileged mode can't be input sink for mouse events sent to privileged windows iirc. It can be good to keep this issue for documentation purposes.
